"use client"

import { Inter } from "@next/font/google"
import AOS from 'aos'
import 'aos/dist/aos.css'
import Head from "next/head"
import Script from "next/script"
import { useEffect } from "react"
import { Button } from "react-bootstrap"
import { HiCursorClick } from "react-icons/hi"
import AboutMe from "../components/AboutMe"
import ContactSection from "../components/ContactMe"
import Projects from "../components/Projects"
import styles from "../styles/Home.module.css"
import HomeMain from "./HomeMain"

const inter = Inter({ subsets: ["latin"] })

export default function Home() {

  useEffect(() => {
    AOS.init({
      easing: 'ease-out-quad',
      duration: 1000,
    });
  }, [])


  return (
    <>
      <Head>
        <title>Agbaje Olayiwola Portfolio</title>
        <meta name="description" content="Generated by Agbaje Ola" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="bower_components/aos/dist/aos.css" />

      </Head>
          <Script src="bower_components/aos/dist/aos.js"></Script> 
      <main className={styles.main}>
        <HomeMain />
        <AboutMe />
        <Projects />
        <ContactSection />

        <div className="default hero-section-desc">
          <p>Clcik Here to return to Default Theme</p>
          <Button
            id="hero-btn1"
            variant="primary"
            onClick={() =>
              document.body.setAttribute("data-theme", "light-theme")
            }
          >
            <div className="innerBtn">
              <p className="hero-section-desc">Here</p>
              <HiCursorClick />
            </div>
          </Button>
        </div>

        {/* <Button
                    id="hero-btn2"
                    variant="secondary"
                    onClick={() =>
                      document.body.setAttribute("data-theme", "dark-theme")
                    }
                  >
                    Dark
                  </Button>
                  <Button
                    id="hero-btn3"
                    variant="success"
                    onClick={() =>
                      document.body.setAttribute("data-theme", "sea-theme")
                    }
                  >
                    Sea Wave
                  </Button> */}
        {/* <Button
                    id="hero-btn4"
                    variant="success"
                    onClick={() =>
                      document.body.setAttribute("data-theme", "sharp-theme")
                    }
                  >
                    Sharp
                  </Button> */}
      </main>
    </>
  )
}
