import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { DarkModeToggle } from "@anatoliygatt/dark-mode-toggle";
import { useContext, useState } from "react";
import MyThemeContext from "../store/myThemeContext";
const inter = Inter({ subsets: ["latin"] });
import { Container, Row, Col, Button } from "react-bootstrap";
import HomeMain from "./HomeMain";
import AboutMe from "../components/AboutMe";
import Projects from "../components/Projects";
import { HiCursorClick } from "react-icons/hi";
import ContactSection from "../components/ContactMe";

export default function Home() {
  return (
    <>
      <Head>
        <title>Agbaje Olayiwola Portfolio</title>
        <meta name="description" content="Generated by Agbaje Ola" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <HomeMain />
        <AboutMe />
        <Projects />
        <ContactSection />

        <div className="default hero-section-desc">
          <p>Clcik Here to return to Default Theme</p>
          <Button
            id="hero-btn1"
            variant="primary"
            onClick={() =>
              document.body.setAttribute("data-theme", "light-theme")
            }
          >
            <div className="innerBtn">
              <p className="hero-section-desc">Here</p>
              <HiCursorClick />
            </div>
          </Button>
        </div>

        {/* <Button
                    id="hero-btn2"
                    variant="secondary"
                    onClick={() =>
                      document.body.setAttribute("data-theme", "dark-theme")
                    }
                  >
                    Dark
                  </Button>
                  <Button
                    id="hero-btn3"
                    variant="success"
                    onClick={() =>
                      document.body.setAttribute("data-theme", "sea-theme")
                    }
                  >
                    Sea Wave
                  </Button> */}
        {/* <Button
                    id="hero-btn4"
                    variant="success"
                    onClick={() =>
                      document.body.setAttribute("data-theme", "sharp-theme")
                    }
                  >
                    Sharp
                  </Button> */}
      </main>
    </>
  );
}
